[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

optimizer = true
optimizer_runs = 200

verbosity = 2

# Fuzz testing configuration
fuzz = { runs = 256 }

gas_reports = ["Counter"]

remappings = [
    "forge-std/=lib/forge-std/src/",
]

[profile.ci]
verbosity = 4
fuzz = { runs = 1000 }

[profile.deep-fuzz]
fuzz = { runs = 10000 }

[fmt]
bracket_spacing = true
line_length = 100
tab_width = 4
