[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

optimizer = true
optimizer_runs = 200

verbosity = 2

# Gas reporting for all contracts
gas_reports = ["Voting"]

# Fuzz testing
fuzz = { runs = 256 }

remappings = [
    "forge-std/=lib/forge-std/src/",
]

[profile.ci]
verbosity = 4
fuzz = { runs = 1000 }

[profile.gas]
gas_reports = ["*"]
verbosity = 3

[fmt]
bracket_spacing = true
line_length = 100
tab_width = 4
